import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/providers/ThemeProvider";
import ClientOnly from "../components/providers/ClientOnly";
import Enhancements from "../components/providers/Enhancements";
import CustomCursor from "@/components/cursor/CustomCursor";
import Header from "@/components/header/Header";
import { telma } from "../lib/fonts"

const themeScript = `
(function () {
  try {
    const storedTheme = localStorage.getItem("theme");
    const systemPrefersDark = window.matchMedia("(prefers-color-scheme: dark)").matches;

    const theme = storedTheme || (systemPrefersDark ? "dark" : "light");

    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  } catch (e) {}
})();
`;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head className={telma.variable}>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${telma.variable} antialiased`}
      >
        <ThemeProvider>
          <Enhancements>
            <div className="m-auto w-full xs:w-4/5 sm:w-9/12 md:w-2/3 xl:w-1/2">
              <Header />
              <main>
                <ClientOnly>
                  {children}
                  <CustomCursor />
                </ClientOnly>
              </main>
            </div>
          </Enhancements>
        </ThemeProvider>
      </body>
    </html>
  );
}
